#!/usr/bin/env bash

function delayedPluginInstall {
    sudo mkdir -p /home/developer/.IdeaIC15/config/plugins
    sudo mkdir -p /home/developer/.IdeaIC15/config/options
    sudo chown developer:developer -R /home/developer/.IdeaIC15

    cd /home/developer/.IdeaIC15/config/plugins/

    echo 'Installing Go plugin'
    wget https://plugins.jetbrains.com/files/5047/22601/Go-0.10.749.zip -O go.zip -q && unzip -q go.zip && rm go.zip

    echo 'Installing .ignore plugin'
    wget https://plugins.jetbrains.com/files/7495/20861/idea-gitignore.jar -O /home/developer/.IdeaIC15/config/plugins/idea-gitignore.jar -q

    echo 'Installing Markdown support plugin'
    wget https://plugins.jetbrains.com/files/7793/22165/markdown.zip -O markdown.zip -q && unzip -q markdown.zip && rm markdown.zip

    # Adding the predefined preferences to IDEA
    cp /home/developer/.jdk.table.xml /home/developer/.IdeaIC15/config/options/jdk.table.xml
}

if [ ! -d /home/developer/.IdeaIC15/config/plugins/Go ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

if [ -d /home/developer/.IdeaIC15 ]; then
    # Ensure proper permissions
    sudo chown developer:developer -R /home/developer/.IdeaIC15
fi

exec /opt/intellij/bin/idea.sh
